# Copyright (c) 2019-2023, NVIDIA CORPORATION.

{% set data = load_file_data("python/pyproject.toml") %}

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: rmm
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=rmm-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=rmm-linux64 # [linux64]
    - SCCACHE_BUCKET
    - SCCACHE_REGION
    - SCCACHE_IDLE_TIMEOUT
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  ignore_run_exports_from:
    - {{ compiler('cuda') }}

requirements:
  build:
    - cmake >=3.23.1,!=3.25.0
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }} {{ cuda_version }}
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - python
    - cudatoolkit ={{ cuda_version }}
    - librmm ={{ version }}
    {% for r in data.get("build-system", {}).get("requires", []) %}
    - {{ r }}
    {% endfor %}
  run:
    - python
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}
    {% for r in data.get("project", {}).get("dependencies", []) %}
    - {{ r }}
    {% endfor %}

test:
  imports:
    - rmm

about:
  home: {{ data.get("project", {}).get("urls", {}).get("Homepage", "") }}
  license: {{ data.get("project", {}).get("license", {}).get("text", "") }}
  license_file:
    {% for e in data.get("tool", {}).get("setuptools", {}).get("license-files", []) %}
    - ../../../{{ e }}
    {% endfor %}
  summary: {{ data.get("project", {}).get("description", "") }}
  dev_url: {{ data.get("project", {}).get("urls", {}).get("Source", "") }}
  doc_url: {{ data.get("project", {}).get("urls", {}).get("Documentation", "") }}
